# Generated by Django 5.2.14 on 2026-05-21 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_page", "0006_interchange_coordinates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crowdreport",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="interchange",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
